### ISSUE TITLE
[2.4.4] After HM01, can re-board S.S. Anne, but when you leave, the game crashes

### ISSUE THREAD

**Issue by BritishCynic** [Vortyne/pureRGB#40]
If you depart SS Anne via something like the Pocket Abra after obtaining HM01, you can re-board it, but if you depart again it goes to a blank screen.

**Comment by Vortyne** [comment]
I recall testing this, but I must have broken it more recently

**Comment by Vortyne** [comment]
It seems the game doesn't crash, it just keeps the palette black when it should be showing the boat leaving

**Comment by Vortyne** [comment]
This is due to a change I made to many maps that replace tile blocks on load in 2.4.0, the maps stay on a black screen until the first time the map's script is run. As a result, certain events that can run before the map's script runs one time can cause the screen to stay black unless I manually reset the palette. In this case I missed a place to manually reset the palette.

I'll fix it in the next version.
