### ISSUE TITLE
Trees disappearing/reappearing on Route 5

### ISSUE THREAD

**Issue by CVerner1** [Vortyne/pureRGB#71]
Trees beyond the fence line on Route 5 randomly disappear/reappear when walking away and returning brings them in/out of frame. This seems to happen randomly, sometimes the glitch doesn't appear however it occurs often enough.  This occurs with trees on both the east and west side of Route 5.

**Comment by Vortyne** [comment]
This is something that happens in the original game and it's just because of how the game deals with the "out of bounds" blocks. One route has trees assigned as its "out of bounds" block, the other has grass as its "out of bounds" block. So if you're in one route, it puts trees, but the other puts grass.
