### ISSUE TITLE
Rival randomly turning away during dialogue after battles

### ISSUE THREAD

**Issue by CVerner1** [Vortyne/pureRGB#72]
After battles with the rival but while still in dialogue the rival sometimes turns away quickly then turns back as if trying to follow the path to leave. This happens throughout dialogue usually after each new text box appears, until dialogue ends. Glitch doesn't always show up, but is noticeable when it does.

**Comment by Vortyne** [comment]
It's caused by an unintentional change back in the early releases, but I don't want to change it back because it might mess with the visuals of new stuff I added unintentionally to bring back the original code.

**Comment by Vortyne** [comment]
I could probably fix it on a case by case basis though so I'll try in the next release

**Comment by Vortyne** [comment]
found an instance of it in oak's lab and fixed, still looking but haven't seen it on other encounters

**Comment by Vortyne** [comment]
I think it's caused by the NPC auto-walking code, it resets the movement bytes of the sprite (like specifying which direction they should stay facing always or whether they can look in different directions occasionally) so maybe if I just reset these to the correct values after the rival walks around it'll fix the issue. I'll try it and put it in the next release.

**Comment by CVerner1** [comment]
> found an instance of it in oak's lab and fixed, still looking but haven't seen it on other encounters

I'd had it happen for every encounter for multiple playthroughs up until at least S.S. Anne, but now this glitch never happens to me even at Oak's lab, so idk what's happening, lol.

**Comment by Vortyne** [comment]
I think I fixed it. Will put in next release.
