### ISSUE TITLE
[Review]: Summarize your review here

### ISSUE THREAD

**Issue by anonimo704** [Vortyne/pureRGB#81]
### Did you finish playing the game before leaving a review?

No

### Review Content

Hello,

I did not finish the game, but I that had to create an account just for leaving a first feedback.

Generally the impression is positive, in particular I wanted to mention

1) Colors/Sprites

There are many options, maybe too many considering that most differences do not really affect gameplay and are minimal (IMHO).
On the other hand, I believe that "real" colors would enhance this game even more.

This is an example of a romhack that colorized the game: https://www.romhacking.net/hacks/1385/

2) Playing as a boy/girl

While it is true that gen1 games did not permit to play as a girl, some romhacks have this option, for example the following one: https://www.romhacking.net/hacks/4205/
Especially considering that green is a girl, it would make sense to have this option in an enhanced gen1 game.

3) Pokemon Yellow

Yellow is a first-gen, and it's missing. 
Pokemon PureYellow!

I imagine it could be just like the existing version with a following Pikachu that does not evolve and is always happy (unless you want to consider to add the friendship system for just one pokemon...).
Maybe it would be nice (for red/green/blue included) to have jesse/james for some extra battles.
I am personally less attached to the other differences since colors and sprites are already integrated, and considering the other changes.
For example, there is little/no need for the characters in yellow for obtaining the other starters.

4) Cinnabar island option is not with the other options

This is a little confusing, having all options together would be better, instead of having everything at one place, and the one option in the PC

5) bug in Mt. Moon?

I think I found a bug in Mt. Moon.
The rock where there is a Ether hidden; when I clicked on it the first time, an empty dialog box was shown.
I do not have a savefile for retesting it for being sure, I played Pokemon_PureRed_v2.6.1

**Comment by Vortyne** [comment]
1. I am not adding full color to the game. Gen 1 does not have full color and I'm not interested in making Gen 1 look like Gen 2. Play gen 2 or perhaps Red++ if you want full color in gen 1.
2. Someone already implemented that in a different branch if you want it. Personally I want to keep gen 1 about Red, a male protagonist, as it was in the original games. That's who this game is about. You are free to change it if you prefer other graphics by changing the code.
3. I don't like pokemon yellow, and am not interested in making a yellow version of this romhack. The code base is different first of all, so it would take a massive effort to convert it.
4. I cannot place it with the other options, because then the player could change it while surfing exactly on the spot the volcano is at. And that would cause a whole lot of complications with changing the map dynamically that I don't want to deal with. This is the entire reason I separated it into a PC options page. I need the player to be in a specific place where changing the option won't cause issues.
5. I'm unable to reproduce that bug, did you transfer a save from an earlier version?

**Comment by anonimo704** [comment]
About 1; I suspected that it, but wanted to give my sincere  opinion

About 2; I'll look for this different branch, thank you for the hint.

About 5; no, I did not transfer the game. But maybe I did not pay enough attention and clicked to fast A, thus the question mark.


I also realized two other things

In another romhack (cant remember which right now) there was an option to hide the dialog if you want to nickname your pokemon.
Since I newer use nicknames, I liked this minor addition a lot.


I incorrectly wrote that the game has the yellow sprites; there are some, but the most that can be switched are about RB and RG, only a small subset has the option to switch to Y, (which I find they match better with the SW97 sprites)
