### ISSUE TITLE
Venusaur always 100% crits when using Razor Leaf 

### ISSUE THREAD

**Issue by ProblematicBulbasaur** [Vortyne/pureRGB#85]
I don't know that much about the game logic and balancing, but I'm playing PureGreen on the latest version (I started the save on 2.5.5, it converted upon loading!) and every single time I use Razor Leaf with my starter Bulbasaur, now Venusaur, it crits. 100%. This is making the game much easier than it should be on the default normal difficulty. Is this intended behaviour?

Playing on Gambette core using the interface MinUI on a Miyoo A30 device, if it helps.
[pure.gb.sav.zip](https://github.com/user-attachments/files/18159364/pure.gb.sav.zip)

(There is no game content on the zip, only the save. The file extension there is part of how MinUI handles files. It replicates the name of the extension from the original file.)

**Comment by Vortyne** [comment]
Yes, it's intended behaviour from the original game. In gen 1, pokemon have higher crit ratios based on their speed. Such that pokemon with 130 base speed like Jolteon have a 25.39% chance of crit on every move. In gen 1, high critical hit ratio moves such as razor leaf, karate chop, etc. multiply your base critical hit rate by 8. This means any pokemon with a crit rate of at least 12.5% will always crit using these moves. Venusaur, with 80 base speed, has a 15.63% chance of crit on each move. This means high crit ratio moves will always crit with venusaur. In fact, unless the pokemon has less than 65 base speed, it will have a 100% crit ratio with these moves. This makes them very useful moves! Yes, it makes venusaur very good early on, but many pokemon can learn karate chop and dish out damage as well! Keep in mind that when you get a critical hit, it will ignore any boosts to your own stats, so you can set these moves up with something like Swords Dance, because they will ignore the boosts. So their is a limit to their damage.
